version: '3'
volumes:
    ldap_data:
services:
  nexus:
    build: .
    image: olblak/nexus:latest
    volumes:
        - ./mock/config_password:/secrets/admin_password
        - ./mock/secret_ldap:/secrets/ldap_password
        - ./postStart.sh:/opt/sonatype/nexus/postStart.sh
    depends_on:
        - ldap
    ports:
        - 8081:8081

  # Don't forget to run /entrypoint/restore, once database is started
  # docker exec -i -t docker_ldap_1 /entrypoint/restore
  # docker exec -i -t docker_ldap_1 /entrypoint/healthcheck
  
  ldap:
    image: jenkinsciinfra/ldap:12-builde29683
    environment: 
        - "OPENLDAP_DEBUG_LEVEL=1"
    volumes:
        - ldap_data:/var/lib/ldap
        - ./mock/ldap/ca.crt:/etc/ssl/certs/ca-certificates.crt
        - ./mock/ldap/ca.crt:/etc/ldap/ssl/cacert.pem
        - ./mock/ldap/ldap.crt:/etc/ldap/ssl/cert.pem
        - ./mock/ldap/ldap.key:/etc/ldap/ssl/privkey.key
        - ./mock/mock.ldif:/var/backups/backup.latest.ldif
